### ISSUE TITLE
setDefaultColorButton(int color) is not working

### ISSUE THREAD

**Issue by monowar1993** [kristiyanP/colorpicker#11]
I am giving a default color each time but it is not ticked using setDefaultColorButton(int color);
Also please provide a better sample at least showing some more features. 
thanks

**Comment by kristiyanP** [comment]
Did you define a color that is existing in your grid? 
Please provide your code.
It should not be called more than once and should always be called with an existing color...

The README contains already all the information that is necessary to use the library
