### ISSUE TITLE
problem with custom set color

### ISSUE THREAD

**Issue by avrpic8** [kristiyanP/colorpicker#13]
Hi my bro.
I have a problem with setColors(ArrayList<String> colorsHexList) method.
when I set my own color by a ArrayList , the dialog nothink show.
What should I do?

this is my code:

ArrayList<String> colorHex = new ArrayList<>();
        colorHex.add("0xFF000000");

        final ColorPicker colorPicker = new ColorPicker(this);
        colorPicker.setOnFastChooseColorListener(new ColorPicker.OnFastChooseColorListener() {
            @Override
            public void setOnFastChooseColorListener(int position, int color) {
                showToast(String.valueOf(color));
            }

            @Override
            public void onCancel(){
                // put code
            }
        }).setColors(colorHex).show();

**Comment by edi233** [comment]
I have the same problem:
final ColorPicker colorPicker = new ColorPicker(activity);
            ArrayList<Integer> colors = new ArrayList<>();
            colors.add("#82B926");
            colors.add("#a276eb");
            colors.add("#6a3ab2");
            colors.add("#666666");
            colors.add("#FFFF00");
            colors.add("#3C8D2F");
            colors.add("#FA9F00");
            colors.add("#FF0000");
            colorPicker.setColors(colors);
and see only white squares

**Comment by ksrpraneeth** [comment]
Yes even i am facing the same problem
