### ISSUE TITLE
the examples dont work

### ISSUE THREAD

**Issue by hvar90** [kristiyanP/colorpicker#14]
WARN - .workspace.NdkWorkspaceManager - NDK support for project 'colorpicker-master' is disabled because it's not a valid Android project
also i tried with only the example and i got 
 WARN - .workspace.NdkWorkspaceManager - NDK support for project 'example' is disabled because it's not a valid Android project 

how can i run the examples ?

**Comment by kristiyanP** [comment]
this depends on your personal environment setup.
https://code.google.com/p/android/issues/detail?id=228424

**If you had problems in executing the demo app with android studio**
Please pull to the latest commit and delete the folder `example` in case you have it. 

Leaving only `colorpicker-library` and `sample` folders.
