### ISSUE TITLE
Gradel build fails

### ISSUE THREAD

**Issue by omushpapa** [kristiyanP/colorpicker#15]
Gradle fails to build with `compile 'petrov.kristiyan:colorpicker-library:1.1.5'` as indicated on the README

Only `compile 'petrov.kristiyan.colorpicker:colorpicker-library:1.1.2'` works

**Comment by kristiyanP** [comment]
Thank you!! 
Looks like the library for some reason was not synched with jcenter
While i wait for the sync with jcenter you can use the 1.1.5 by adding the following maven repo in your project gradle
 ```
allprojects {
    repositories {
          maven {  url "https://dl.bintray.com/petrovkristiyan/maven" }
          ... // other repositories such as jcenter
   }
}
```

**Comment by kristiyanP** [comment]
bintray fixed the issue, now is possible to use the library directly from jcenter.
Without adding the additional maven repository
