### ISSUE TITLE
when the update on support 23.2.0 ?

### ISSUE THREAD

**Issue by TarasOryshhij** [kristiyanP/colorpicker#2]
![dc7b81634ffbb6daec79e001ccc8d1a942f9268127f18529ca pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/17122827/13541282/09a5f604-e264-11e5-8297-41484e88b788.jpg)

**Comment by kristiyanP** [comment]
com.android.support:recyclerview-v7:23.2.0 is already used in version 1.0.4

**Comment by TarasOryshhij** [comment]
but if i used 23.2.0  i see this picture (setGravity does not help).

**Comment by kristiyanP** [comment]
in version 1.0.4 there is no more setGravity
change gradle to
compile 'petrov.kristiyan.colorpicker:colorpicker-library:1.0.4
