### ISSUE TITLE
Gradle build failed

### ISSUE THREAD

**Issue by ulan17** [kristiyanP/colorpicker#24]
I've tried to use ` implementation 'petrov.kristiyan:colorpicker-library:1.1.9'`. So I've got gradle build fail.

Only works until ` implementation 'petrov.kristiyan:colorpicker-library:1.1.8'`

**Comment by kristiyanP** [comment]
since v1.1.9  is using androidx, you should consider to upgrade to androidx
If you don't want to update yet to androidx follow the suggested solution in the build fail error
