### ISSUE TITLE
use in Fragment?

### ISSUE THREAD

**Issue by Jvasileiou** [kristiyanP/colorpicker#27]
I use the library in Fragment and i take this error "java.lang.IllegalStateException : You need to use a Theme.AppCompat theme (or descendant) with this activity" ..i read that the problem caused because the activity i am trying to apply the library dialog theme to is extending ActionBarActivity which requires the AppCompat theme to be applied . I tried many solutions but i didnt manage to fix it .
Some help please ?

Thank y and i believe your colorpicker is great!

**Comment by kristiyanP** [comment]
Have you tried all the solutions proposed here: https://stackoverflow.com/questions/21814825/you-need-to-use-a-theme-appcompat-theme-or-descendant-with-this-activity?

**Comment by Jvasileiou** [comment]
Finally i create my own color picker. I do not use your library.But i want to say that your job is very good.Congrats
Thank you
----
Vasileiou Ι. 

    Στις Δευτέρα, 8 Απριλίου 2019, 11:12:13 μ.μ. EEST, ο χρήστης Kristiyan Petrov <notifications@github.com> έγραψε:  
 
 
Have you tried all the solutions proposed here: https://stackoverflow.com/questions/21814825/you-need-to-use-a-theme-appcompat-theme-or-descendant-with-this-activity?

**Comment by kristiyanP** [comment]
ok then I am closing the issue

**Comment by Jvasileiou** [comment]
Yes.Thank you

Στάλθηκε από το Ταχυδρομείο Yahoo σε Android 
 
  Στις Τετ, 10 Απρ, 2019 στις 8:42 μ.μ., ο χρήστηςKristiyan Petrov<notifications@github.com> έγραψε:   
ok then I am closing the issue
