### ISSUE TITLE
ColorPicker DP/PX issue

### ISSUE THREAD

**Issue by mobilekosmos** [kristiyanP/colorpicker#29]
The method setColorButtonSize requests integer DP that you then convert to PX?!?!:

setColorButtonSize(dip2px(colorButtonWidth, context)

We are passing 48 to the method because this is the min. touchable target size recommended by the Accessibility Scanner. The Scanner then says the views have only 47, so something is wrong in your functions. Anyways why will you set PX if its always recommended to set the sizes of views in DP?
Also dip2px request "float" where you are using it with "int".

How can I now make sure I always get 48dp width and height?

**Comment by kristiyanP** [comment]
Thank you for reporting the issue.
I would gladly accept a PR.
