### ISSUE TITLE
setColors(int... colorInt) issue:  Colorpicker doesn't show the correct colors after use it

### ISSUE THREAD

**Issue by pablobae** [kristiyanP/colorpicker#32]
The showed colors are not the  assigned colors with setColors(int... colors) method.

![imagen](https://user-images.githubusercontent.com/33727260/67218415-a1ae4c80-f426-11e9-8bee-0d72fab7336d.png)

And this is the result:
![imagen](https://user-images.githubusercontent.com/33727260/67218550-dde1ad00-f426-11e9-8602-c1b1239011a3.png)

List of colors:

![imagen](https://user-images.githubusercontent.com/33727260/67219436-51d08500-f428-11e9-8aba-c0a32958db1f.png)

**Comment by kristiyanP** [comment]
setColors accepts Color ints not resource ids.
To show the correct colors set it like this:
```java
colorPicker.setColors(ContextCompat.getColor(context, R.color.md_red_300),ContextCompat.getColor(context, R.color.md_pink_300))

```
