### ISSUE TITLE
Layout doesn't utilize  space on tablets.

### ISSUE THREAD

**Issue by justinmeiners** [kristiyanP/colorpicker#6]
The color picker is now working on tablets, but is not utilizing the space very well. Attached is a screenshot. In this screenshot I am using an array of colors. On vertical layouts all the colors are displayed, in this horizontal layout I have to scroll despite the extra space.

Let me know if you need anymore information or want me to take a stab and implementing a fix.

![screenshot_2016-04-01-16-45-33](https://cloud.githubusercontent.com/assets/3220045/14222073/ac685640-f829-11e5-9b8e-ed9d0cf00130.png)

**Comment by kristiyanP** [comment]
should be fixed with version 1.0.6

**Comment by justinmeiners** [comment]
Thank you for your fast response.
