### ISSUE TITLE
Context instead of Activity?

### ISSUE THREAD

**Issue by 12people** [kristiyanP/colorpicker#7]
I'm calling the picker from an OnClickAdapter inside a RecyclerHolder, where I only have access to an unspecified Context. Right now, I'm casting Context to Activity, but that's a pretty ugly way to do things. I've taken a quick look at the code and it seems like Activity could be exchanged for the more generic Context. Would that be possible? Is there a reason for prefering Activity?

**Comment by 12people** [comment]
When exchanging Activity for Context, instead of calling getLayoutInflater(), call LayoutInflater.from(context) .

**Comment by kristiyanP** [comment]
Changed in version 1.1.0
