### ISSUE TITLE
Default strings aren't localized

### ISSUE THREAD

**Issue by 12people** [kristiyanP/colorpicker#8]
It'd be nice if the strings in the library were localized. To do that, we should use string resources instead of hard-coded string constants.

**Comment by kristiyanP** [comment]
from version 1.1.0 strings are localized

**Comment by tsl-developteam** [comment]
How to do it?

**Comment by kristiyanP** [comment]
You can either overwrite the following strings or add your custom buttons.

```xml
<string name="colorpicker_dialog_title">Choose the color</string>
<string name="colorpicker_dialog_cancel">CANCEL</string>
<string name="colorpicker_dialog_ok">OK</string>
```
